### ISSUE TITLE
Author with email and username not parsing correctly

### ISSUE THREAD

**Issue by SamWilsn** [ethereum/eip-review-bot#270]
See https://github.com/ethereum/EIPs/pull/6956, specifically at https://github.com/ethereum/EIPs/pull/6956/commits/9d188578511cb53c00ebe0910043ab50fb40a248.

Bot generated a comment like:

![image](https://github.com/ethereum/eip-review-bot/assets/57262657/c61db039-31ed-4482-b960-3b9d4fe73134)

**Comment by tbergmueller** [comment]
I removed the email-addresses in the mentioned PR, since we want to move forward and this bug is still open.

- https://github.com/ethereum/EIPs/pull/6956/commits/1884f6d43c201b03ae7e99701516e30975e1a72d 
- This caused the bot to accept author-review (state changed from a-review to e-review)
- The only issue for eth-bot now is the missing review from editors, see https://github.com/ethereum/EIPs/actions/runs/5031311962

![image](https://github.com/ethereum/eip-review-bot/assets/2257335/38482897-961d-4413-8be5-1b21235c1486)

**Comment by Pandapip1** [comment]
Found the bug.
